export const LOAD_WORDS = 'LOAD_WORDS';
export const CHANGE_MODAL_AUTH = 'CHANGE_MODAL_AUTH';
export const CHANGE_NAME_MINIGAME = 'CHANGE_NAME_MINIGAME';
export const LOAD_WORDS_AUTH = 'LOAD_WORDS_AUTH';
export const END_AUDIO_WORDS = 'END_AUDIO_WORDS';
export const PLAY_AUDIO_WORDS = 'PLAY_AUDIO_WORDS';
